# Generated by Django 4.2.25 on 2025-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcoleBiblique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("special", "Événement Spécial"),
                            ("conference", "Conférence"),
                            ("youth", "Jeunesse"),
                            ("monthly", "Mensuel"),
                            ("prayer", "Prière"),
                            ("worship", "Adoration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("max_participants", models.IntegerField(default=0)),
                ("current_participants", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("registration_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
