# Generated by Django 4.2.25 on 2025-11-05 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EcoleBiblique", "0002_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "number_of_participants",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de participants"
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(blank=True, verbose_name="Demandes spéciales"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("cancelled", "Annulée"),
                            ("waiting_list", "Liste d'attente"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "confirmation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="EcoleBiblique.event",
                        verbose_name="Événement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription à un événement",
                "verbose_name_plural": "Inscriptions aux événements",
                "ordering": ["-registration_date"],
                "indexes": [
                    models.Index(
                        fields=["event", "status"],
                        name="EcoleBibliq_event_i_31dcf9_idx",
                    ),
                    models.Index(
                        fields=["email", "registration_date"],
                        name="EcoleBibliq_email_0033be_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.CheckConstraint(
                check=models.Q(("number_of_participants__gt", 0)),
                name="positive_number_of_participants",
            ),
        ),
    ]
