# Generated by Django 4.2.25 on 2025-11-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EcoleBiblique", "0003_eventregistration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonné à la newsletter",
                "verbose_name_plural": "Abonnés à la newsletter",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
