# Generated by Django 4.2.25 on 2025-11-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("EcoleBiblique", "0004_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("all", "Tous les lieux"),
                            ("cergy", "Cergy"),
                            ("paris", "Paris"),
                            ("yaounde", "Yaoundé"),
                            ("douala", "Douala"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Lieu préféré",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(default=list, verbose_name="Catégories préférées"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'inscription"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Token de sécurité"
                    ),
                ),
            ],
            options={
                "verbose_name": "Abonnement aux alertes événements",
                "verbose_name_plural": "Abonnements aux alertes événements",
                "ordering": ["-subscribed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="churchlocation",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "Lieu d'église",
                "verbose_name_plural": "Lieux d'église",
            },
        ),
        migrations.AddField(
            model_name="churchlocation",
            name="pastor_in_charge",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Pasteur responsable",
            ),
        ),
        migrations.AddField(
            model_name="churchlocation",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Ordre d’affichage"
            ),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("regular", "Régulier"),
                            ("special", "Spécial"),
                            ("conference", "Conférence"),
                            ("prayer", "Prière"),
                            ("youth", "Jeunesse"),
                            ("social", "Social"),
                        ],
                        max_length=20,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Date et heure de début"),
                ),
                ("end_date", models.DateTimeField(verbose_name="Date et heure de fin")),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Événement récurrent"
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modèle de récurrence"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="calendar/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "registration_required",
                    models.BooleanField(
                        default=False, verbose_name="Inscription requise"
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(blank=True, verbose_name="Lien d'inscription"),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        default=0, verbose_name="Nombre maximum de participants"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="En vedette"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EcoleBiblique.churchlocation",
                        verbose_name="Lieu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement calendrier",
                "verbose_name_plural": "Événements calendrier",
                "ordering": ["start_date"],
            },
        ),
    ]
